/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Guice_basic;

import com.google.inject.AbstractModule;
import com.google.inject.Guice;
import com.google.inject.Inject;
import com.google.inject.Injector;
import com.google.inject.Scopes;
import com.google.inject.name.Named;
import com.google.inject.name.Names;

public class App {

	public static void main(String[] args) {
	      Injector injector = Guice.createInjector(new BindModule());
	      Greetings Obj = injector.getInstance(Greetings.class);
	      Obj.sayHi(); 
	      Greetings Obj1 = injector.getInstance(Greetings.class);
	      Obj1.sayHi(); 
	      
	      boolean check = Obj.getHiInstance() == Obj1.getHiInstance();
	      System.out.println("both Class are equal: "+ check);
	      boolean check1 = Obj == Obj1 ;
	      System.out.println("both Greetings Objects are equal: "+ check1);
	   } 
	}

	class Greetings {
	   HiInterface HiInstance;

	   @Inject
	   public Greetings(HiInterface HiInstance) {
		   this.HiInstance = HiInstance;
	   }

	   public HiInterface getHiInstance() {
		   return HiInstance;
	   }

//	   public void setHiInstance(HiInterface hiInstance) {
//		   HiInstance = hiInstance;
//	   }

	   public void sayHi(){
		   System.out.println("It's GreetingsClass !");
		   HiInstance.hi();
	   }
	}
	
	class SubClass extends Greetings{
		
		@Inject
		public SubClass(HiInterface HiInstance) {
			super(HiInstance);
		}
		
		@Override
		public void sayHi() {
			System.out.println("It's SubClass !");
			HiInstance.hi();
		}
		
	}
	
	//Binding Module
	class BindModule extends AbstractModule {

	   @Override
	   protected void configure() {
	      bind(HiInterface.class).to(HiClass.class).in(Scopes.SINGLETON);
	      bind(Greetings.class).to(SubClass.class).in(Scopes.SINGLETON);
//	      bind(Greetings.class).to(SubClass.class);
//	      bind(Greetings.class).in(Scopes.SINGLETON);
	      bind(Integer.class).annotatedWith(Names.named("id")).toInstance(101);
	      bind(String.class).annotatedWith(Names.named("name")).toInstance("Red");
	   } 
	}

	//spell checker interface
	interface HiInterface {
	   public void hi();
	}


	//spell checker implementation
	class HiClass implements HiInterface {
		
		private Integer id;
		private String name;
		
	   @Inject
	   public HiClass(@Named("id") Integer id, @Named("name") String name) {
			super();
			this.id = id;
			this.name = name;
		}

	@Override
	   public void hi() {
	      System.out.println("Hello !!!" );
	      System.out.println("Here id: "+ id +" and name: "+ name );
	   } 
}
